# Generated by Django 2.2.4 on 2019-09-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicaMedica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.IntegerField()),
                ('description', models.TextField()),
                ('sintomas', models.TextField()),
                ('prescripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
