# Generated by Django 2.2.4 on 2019-09-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicaMedica', '0003_clientprofile_type'),
        ('ClinicaMedica', '0002_cita'),
    ]

    operations = [
    ]
